SELECT SO.*,
SOI.SALESORDERITEM,
SOI.PRODUCTID,
SOI.NOTEID AS SOI_NOTEID,
SOI.CURRENCY AS SOI_CURRENCY,
SOI.GROSSAMOUNT AS SOI_GROSSAMOUNT,
SOI.NETAMOUNT AS SOI_NETAMOUNT,
SOI.TAXAMOUNT AS SOI_TAXAMOUNT,
SOI.ITEMATPSTATUS,
SOI.OPITEMPOS,
SOI.QUANTITY,
SOI.QUANTITYUNIT,
SOI.DELIVERYDATE,
{{add_audit_cols(['SO.SALESORDERID','SO.CHANGEDBY','SO.CHANGEDAT'])}} 
FROM {{ref('salesorder')}} SO  
LEFT JOIN {{ref('salesorderitem')}} SOI ON SO.SALESORDERID = SOI.SALESORDERID